name: adapters_flutter
description: The repository contains new versions of adapters for dart test frameworks.
version: 2.0.0
repository: https://github.com/testit-tms/adapters-flutter
homepage: https://pub.dev/packages/adapters_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  logger: any
  path: any
  properties: any
  synchronized: any
  uuid: any
  flutter_test:
    sdk: flutter
  mime: any
  http_parser: any
  test_api: any
  meta: any
  http: any

dev_dependencies:
  flutter_lints: any
