name: testit_adapter_flutter
description: The repository contains new versions of adapters for dart test frameworks.
version: 3.1.0
repository: https://github.com/testit-tms/adapters-flutter/
homepage: https://testit.software/

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  http_parser: ^4.0.2
  logger: ^2.3.0
  meta: ^1.9.1
  mime: ^1.0.4
  path: ^1.8.3
  properties: ^2.1.1
  synchronized: ^3.1.0+1
  test_api: '>=0.5.1 <2.0.0'
  testit_api_client_dart: '>=1.1.1 < 1.1.2'
  universal_io: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
